apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodejs
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        command:
        - "numactl"
        - "--interlevel=all"
        - "mongod"
        - "--wiredTigerCacheSizeGB"
        - "0.1"
        - "--bind_ip"
        - "0.0.0.0"
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: password
              name: mongo-sec
